### PR TITLE
Add talk for KDE Notifications

### PR DESCRIPTION
**Pull request by farribeiro**

### CODE REVIEW

**Comment by Newbytee** [comment]
Strange that the CI failed like that. I'll see if I can look into it soon.

**Comment by Newbytee** [comment]
I just ran this locally and it finished fine. Let's try again I suppose.

**Comment by Newbytee** [comment]
bot, build

**Comment by farribeiro** [comment]
Most likely is appstream

**Comment by Newbytee** [comment]
Could you rebase this on master? Build should be fixed now.

**Comment by farribeiro** [comment]
Yes

**Comment by Newbytee** [comment]
bot, build

**Comment by Newbytee** [comment]
Thanks!

**Pull request merged**
